spring:
  application:
    name: chat-backend-api

  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: '123456'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: minha-senha-super-secreta-123